extends:
  - plugin:angular/johnpapa
  - google
globals:
  goog: false
plugins:
  - mocha
env:
  browser: true
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent: [error, 2]
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  no-unused-vars:
    - warn
    # Account for closure compiler conventions. See docs/closure-compiler.md
    # Ignores: MDC[PascalCase]Adapter (records), [PascalCase]Type (typedefs)
    - varsIgnorePattern: ^(?:(?:MDC(?:(?:[A-Z][a-z0-9]+)+)Adapter)|(?:(?:(?:[A-Z][a-z0-9]+)+)Type))$

  # is complete
  require-jsdoc: off
  valid-jsdoc: off

  prefer-const: error
  no-console: error

  angular/function-type: [1, "named"]
  angular/file-name: off
