version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10-browsers

    working_directory: ~/mdc

    branches:
      ignore:
        - gh-pages
        - /no-test-.*/

    steps:
      - checkout

      - restore_cache:
          key: v1-repo-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Installing Dependencies
          command: npm install

      - save_cache:
          key: v1-repo-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/mdc/node_modules

      - run:
          name: Running Lint
          command: npm run lint

      - run:
          name: Building Distributions
          command: "npm run build:min"

      - run:
          name: Running Unit Tests
          command: "npm run test:ci"

      - store_test_results:
          path: ~/mdc/test/

      - store_artifacts:
          path: ~/mdc/dist/
