defaults: &defaults
  working_directory: ~/mdc
  docker:
      - image: circleci/node:6.10-browsers


version: 2
jobs:
  install:
    docker:
        - image: circleci/node:6.10-browsers
    working_directory: ~/
    steps:
      - checkout:
          path: ~/mdc

      - restore_cache:
          key: v1-repo-deps-{{ checksum "~/mdc/package-lock.json" }}

      - run:
          name: Installing Dependencies
          command: cd ~/mdc && npm install

      - save_cache:
          key: v1-repo-deps-{{ checksum "~/mdc/package-lock.json" }}
          paths:
            - ~/mdc/node_modules

      - persist_to_workspace:
          root: .
          paths:
            - mdc/*

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running Lint
          command: npm run lint

  build_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Building Development Distribution
          command: "npm run build"

  build_prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Building Production Distribution
          command: "npm run build:min"

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running Unit Tests
          command: "npm run test:ci"

      - store_test_results:
          path: ~/mdc/test/

      - store_artifacts:
          path: ~/mdc/dist/

  deploy_demo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Copy Distributible to Demo
          command: cp -R ~/mdc/dist ~/mdc/demos/assets

      - run:
          name: Copy AngularJS to Demo
          command: cp -R ~/mdc/node_modules/angular ~/mdc/demos/angular

      - run:
          name: Build Demo CSS
          command: npm run build:demos

      - deploy:
          name: Deploy to GH Pages
          command: npm run deploy:pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install

      - lint:
          requires:
            - install

      - build_dev:
          requires:
            - install

      - build_prod:
          requires:
            - install

      - test:
          requires:
            - lint
            - build_dev
            - build_prod

      - deploy_demo:
          requires:
            - test
          filters:
            tags:
              ignore: /skip-.*/